#!/usr/bin/env python3
"""Refresh the acknowledgements for direct Rust and npm dependencies."""

import json
import os
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CARGO = tomllib.loads((ROOT / "src-tauri/Cargo.toml").read_text())
CARGO_LOCK = tomllib.loads((ROOT / "src-tauri/Cargo.lock").read_text())
NPM = json.loads((ROOT / "package.json").read_text())


def rust_license(name: str, spec: object) -> dict:
    version = spec if isinstance(spec, str) else spec["version"]
    parts = version.lstrip("^~=").split(".")
    prefix = (".".join(parts[:2]) if parts[0] == "0" and len(parts) > 1 else parts[0]) + "."
    roots = [Path(os.environ.get("CARGO_HOME", Path.home() / ".cargo")), Path.home() / ".cargo"]
    locked = [p["version"] for p in CARGO_LOCK["package"] if p["name"] == name and p["version"].startswith(prefix)]
    if not locked:
        raise RuntimeError(f"Missing locked crate: {name} {version}")
    resolved = max(locked, key=lambda v: tuple(int(part) for part in v.split(".")[:3]))
    crates = [p for root in roots for p in (root / "registry/src").glob(f"*/{name}-{resolved}/Cargo.toml")]
    if not crates:
        raise RuntimeError(f"Missing downloaded crate: {name} {resolved}")
    manifest = tomllib.loads(crates[0].read_text())["package"]
    return {
        "name": name,
        "version": manifest["version"],
        "repository": manifest.get("repository"),
        "license": manifest.get("license") or "Unknown",
    }


def npm_license(name: str) -> dict:
    manifest = json.loads((ROOT / "node_modules" / name / "package.json").read_text())
    repository = manifest.get("repository")
    if isinstance(repository, dict):
        repository = repository.get("url")
    if isinstance(repository, str) and repository.startswith("git+"):
        repository = repository[4:]
    return {
        "name": name,
        "version": manifest["version"],
        "repository": repository,
        "license": manifest.get("license") or "Unknown",
    }


cargo_names = set().union(*(CARGO.get(group, {}) for group in ("dependencies", "build-dependencies", "dev-dependencies")))
cargo_licenses = [rust_license(name, next(CARGO[group][name] for group in ("dependencies", "build-dependencies", "dev-dependencies") if name in CARGO.get(group, {}))) for name in sorted(cargo_names)]
npm_names = set(NPM["dependencies"]) | set(NPM["devDependencies"])
npm_licenses = [npm_license(name) for name in sorted(npm_names)]

out = ROOT / "src/licenses.ts"
out.write_text(
    "// Generated by tools/collect_licenses.py.\n"
    "export type License = { name: string; version?: string; repository: string | null; license: string };\n"
    f"export const cargoLicenses: License[] = {json.dumps(cargo_licenses, indent=2)};\n"
    f"export const npmLicenses: License[] = {json.dumps(npm_licenses, indent=2)};\n"
)
