// Generated by tools/collect_licenses.py.
export type License = { name: string; version?: string; repository: string | null; license: string };
export const cargoLicenses: License[] = [
  {
    "name": "arc-swap",
    "version": "1.6.0",
    "repository": "https://github.com/vorner/arc-swap",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "assert_cmd",
    "version": "2.0.7",
    "repository": "https://github.com/assert-rs/assert_cmd.git",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "core-foundation",
    "version": "0.9.3",
    "repository": "https://github.com/servo/core-foundation-rs",
    "license": "MIT / Apache-2.0"
  },
  {
    "name": "crossbeam",
    "version": "0.8.2",
    "repository": "https://github.com/crossbeam-rs/crossbeam",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "directories",
    "version": "4.0.1",
    "repository": "https://github.com/soc/directories-rs",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "fsevent-stream",
    "version": "0.2.3",
    "repository": "https://github.com/PhotonQuantum/fsevent-stream",
    "license": "MIT"
  },
  {
    "name": "futures",
    "version": "0.3.25",
    "repository": "https://github.com/rust-lang/futures-rs",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "itertools",
    "version": "0.10.5",
    "repository": "https://github.com/rust-itertools/itertools",
    "license": "MIT/Apache-2.0"
  },
  {
    "name": "jwalk",
    "version": "0.8.1",
    "repository": "https://github.com/byron/jwalk",
    "license": "MIT"
  },
  {
    "name": "libc",
    "version": "0.2.189",
    "repository": "https://github.com/rust-lang/libc",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "maplit",
    "version": "1.0.2",
    "repository": "https://github.com/bluss/maplit",
    "license": "MIT/Apache-2.0"
  },
  {
    "name": "moka",
    "version": "0.9.6",
    "repository": "https://github.com/moka-rs/moka",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "once_cell",
    "version": "1.21.4",
    "repository": "https://github.com/matklad/once_cell",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "parking_lot",
    "version": "0.12.1",
    "repository": "https://github.com/Amanieu/parking_lot",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "regex",
    "version": "1.13.1",
    "repository": "https://github.com/rust-lang/regex",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "sentry",
    "version": "0.29.1",
    "repository": "https://github.com/getsentry/sentry-rust",
    "license": "Apache-2.0"
  },
  {
    "name": "serde",
    "version": "1.0.229",
    "repository": "https://github.com/serde-rs/serde",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "serde_json",
    "version": "1.0.151",
    "repository": "https://github.com/serde-rs/json",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "serde_yaml",
    "version": "0.9.16",
    "repository": "https://github.com/dtolnay/serde-yaml",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "shellexpand",
    "version": "3.0.0",
    "repository": "https://gitlab.com/ijackson/rust-shellexpand",
    "license": "MIT/Apache-2.0"
  },
  {
    "name": "tap",
    "version": "1.0.1",
    "repository": "https://github.com/myrrlyn/tap",
    "license": "MIT"
  },
  {
    "name": "tauri",
    "version": "2.9.5",
    "repository": "https://github.com/tauri-apps/tauri",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-build",
    "version": "2.6.3",
    "repository": "https://github.com/tauri-apps/tauri",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-autostart",
    "version": "2.5.1",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-dialog",
    "version": "2.6.0",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-opener",
    "version": "2.5.3",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tempfile",
    "version": "3.3.0",
    "repository": "https://github.com/Stebalien/tempfile",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "thiserror",
    "version": "1.0.69",
    "repository": "https://github.com/dtolnay/thiserror",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "tracing",
    "version": "0.1.44",
    "repository": "https://github.com/tokio-rs/tracing",
    "license": "MIT"
  },
  {
    "name": "tracing-subscriber",
    "version": "0.3.16",
    "repository": "https://github.com/tokio-rs/tracing",
    "license": "MIT"
  },
  {
    "name": "ts-rs",
    "version": "12.0.1",
    "repository": "https://github.com/Aleph-Alpha/ts-rs",
    "license": "MIT"
  },
  {
    "name": "vergen",
    "version": "7.4.4",
    "repository": "https://github.com/rustyhorde/vergen",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "xattr",
    "version": "1.0.0",
    "repository": "https://github.com/Stebalien/xattr",
    "license": "MIT/Apache-2.0"
  }
];
export const npmLicenses: License[] = [
  {
    "name": "@element-plus/icons-vue",
    "version": "2.3.2",
    "repository": "https://github.com/element-plus/element-plus-icons.git",
    "license": "MIT"
  },
  {
    "name": "@tauri-apps/api",
    "version": "2.9.1",
    "repository": "https://github.com/tauri-apps/tauri.git",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "@tauri-apps/cli",
    "version": "2.11.4",
    "repository": "https://github.com/tauri-apps/tauri.git",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "@tauri-apps/plugin-autostart",
    "version": "2.5.1",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "@tauri-apps/plugin-dialog",
    "version": "2.6.0",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "@tauri-apps/plugin-opener",
    "version": "2.5.5",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "@types/node",
    "version": "26.6.1",
    "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
    "license": "MIT"
  },
  {
    "name": "@unocss/preset-icons",
    "version": "66.10.5",
    "repository": "https://github.com/unocss/unocss.git",
    "license": "MIT"
  },
  {
    "name": "@unocss/preset-wind4",
    "version": "66.10.5",
    "repository": "https://github.com/unocss/unocss.git",
    "license": "MIT"
  },
  {
    "name": "@unocss/reset",
    "version": "66.10.5",
    "repository": "https://github.com/unocss/unocss.git",
    "license": "MIT"
  },
  {
    "name": "@unocss/vite",
    "version": "66.10.5",
    "repository": "https://github.com/unocss/unocss.git",
    "license": "MIT"
  },
  {
    "name": "@vitejs/plugin-vue",
    "version": "6.0.9",
    "repository": "https://github.com/vitejs/vite-plugin-vue.git",
    "license": "MIT"
  },
  {
    "name": "element-plus",
    "version": "2.14.6",
    "repository": "https://github.com/element-plus/element-plus.git",
    "license": "MIT"
  },
  {
    "name": "pinia",
    "version": "3.0.4",
    "repository": "https://github.com/vuejs/pinia.git",
    "license": "MIT"
  },
  {
    "name": "typescript",
    "version": "7.0.2",
    "repository": "https://github.com/microsoft/TypeScript.git",
    "license": "Apache-2.0"
  },
  {
    "name": "unocss",
    "version": "66.10.5",
    "repository": "https://github.com/unocss/unocss.git",
    "license": "MIT"
  },
  {
    "name": "vite",
    "version": "7.3.6",
    "repository": "https://github.com/vitejs/vite.git",
    "license": "MIT"
  },
  {
    "name": "vue",
    "version": "3.5.43",
    "repository": "https://github.com/vuejs/core.git",
    "license": "MIT"
  },
  {
    "name": "vue-i18n",
    "version": "11.4.12",
    "repository": "https://github.com/intlify/vue-i18n.git",
    "license": "MIT"
  },
  {
    "name": "vue-router",
    "version": "4.6.4",
    "repository": "https://github.com/vuejs/router.git",
    "license": "MIT"
  }
];
