// Generated by tools/collect_licenses.py.
export type License = { name: string; version?: string; repository: string | null; license: string };
export const cargoLicenses: License[] = [
  {
    "name": "arc-swap",
    "version": "1.6.0",
    "repository": "https://github.com/vorner/arc-swap",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "assert_cmd",
    "version": "2.0.7",
    "repository": "https://github.com/assert-rs/assert_cmd.git",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "cocoa",
    "version": "0.24.1",
    "repository": "https://github.com/servo/core-foundation-rs",
    "license": "MIT / Apache-2.0"
  },
  {
    "name": "core-foundation",
    "version": "0.9.3",
    "repository": "https://github.com/servo/core-foundation-rs",
    "license": "MIT / Apache-2.0"
  },
  {
    "name": "crossbeam",
    "version": "0.8.2",
    "repository": "https://github.com/crossbeam-rs/crossbeam",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "directories",
    "version": "4.0.1",
    "repository": "https://github.com/soc/directories-rs",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "eyre",
    "version": "0.6.8",
    "repository": "https://github.com/yaahc/eyre",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "fsevent-stream",
    "version": "0.2.3",
    "repository": "https://github.com/PhotonQuantum/fsevent-stream",
    "license": "MIT"
  },
  {
    "name": "futures",
    "version": "0.3.25",
    "repository": "https://github.com/rust-lang/futures-rs",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "itertools",
    "version": "0.10.5",
    "repository": "https://github.com/rust-itertools/itertools",
    "license": "MIT/Apache-2.0"
  },
  {
    "name": "jwalk",
    "version": "0.8.1",
    "repository": "https://github.com/byron/jwalk",
    "license": "MIT"
  },
  {
    "name": "libc",
    "version": "0.2.189",
    "repository": "https://github.com/rust-lang/libc",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "maplit",
    "version": "1.0.2",
    "repository": "https://github.com/bluss/maplit",
    "license": "MIT/Apache-2.0"
  },
  {
    "name": "moka",
    "version": "0.9.6",
    "repository": "https://github.com/moka-rs/moka",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "objc",
    "version": "0.2.7",
    "repository": "http://github.com/SSheldon/rust-objc",
    "license": "MIT"
  },
  {
    "name": "once_cell",
    "version": "1.21.4",
    "repository": "https://github.com/matklad/once_cell",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "parking_lot",
    "version": "0.12.1",
    "repository": "https://github.com/Amanieu/parking_lot",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "regex",
    "version": "1.13.1",
    "repository": "https://github.com/rust-lang/regex",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "sentry",
    "version": "0.29.1",
    "repository": "https://github.com/getsentry/sentry-rust",
    "license": "Apache-2.0"
  },
  {
    "name": "serde",
    "version": "1.0.229",
    "repository": "https://github.com/serde-rs/serde",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "serde_json",
    "version": "1.0.151",
    "repository": "https://github.com/serde-rs/json",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "serde_yaml",
    "version": "0.9.16",
    "repository": "https://github.com/dtolnay/serde-yaml",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "shellexpand",
    "version": "3.0.0",
    "repository": "https://gitlab.com/ijackson/rust-shellexpand",
    "license": "MIT/Apache-2.0"
  },
  {
    "name": "tap",
    "version": "1.0.1",
    "repository": "https://github.com/myrrlyn/tap",
    "license": "MIT"
  },
  {
    "name": "tauri",
    "version": "2.9.5",
    "repository": "https://github.com/tauri-apps/tauri",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-build",
    "version": "2.6.3",
    "repository": "https://github.com/tauri-apps/tauri",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-autostart",
    "version": "2.5.1",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-dialog",
    "version": "2.6.0",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-opener",
    "version": "2.5.3",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tempfile",
    "version": "3.3.0",
    "repository": "https://github.com/Stebalien/tempfile",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "thiserror",
    "version": "1.0.69",
    "repository": "https://github.com/dtolnay/thiserror",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "tracing",
    "version": "0.1.44",
    "repository": "https://github.com/tokio-rs/tracing",
    "license": "MIT"
  },
  {
    "name": "tracing-subscriber",
    "version": "0.3.16",
    "repository": "https://github.com/tokio-rs/tracing",
    "license": "MIT"
  },
  {
    "name": "ts-rs",
    "version": "12.0.1",
    "repository": "https://github.com/Aleph-Alpha/ts-rs",
    "license": "MIT"
  },
  {
    "name": "vergen",
    "version": "7.4.4",
    "repository": "https://github.com/rustyhorde/vergen",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "window-vibrancy",
    "version": "0.6.0",
    "repository": "https://github.com/tauri-apps/tauri-plugin-vibrancy",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "xattr",
    "version": "1.0.0",
    "repository": "https://github.com/Stebalien/xattr",
    "license": "MIT/Apache-2.0"
  }
];
export const npmLicenses: License[] = [
  {
    "name": "@emotion/cache",
    "version": "11.14.0",
    "repository": "https://github.com/emotion-js/emotion/tree/main/packages/cache",
    "license": "MIT"
  },
  {
    "name": "@emotion/react",
    "version": "11.14.0",
    "repository": "https://github.com/emotion-js/emotion/tree/main/packages/react",
    "license": "MIT"
  },
  {
    "name": "@emotion/serialize",
    "version": "1.3.3",
    "repository": "https://github.com/emotion-js/emotion/tree/main/packages/serialize",
    "license": "MIT"
  },
  {
    "name": "@emotion/server",
    "version": "11.11.0",
    "repository": "https://github.com/emotion-js/emotion/tree/main/packages/server",
    "license": "MIT"
  },
  {
    "name": "@emotion/styled",
    "version": "11.14.1",
    "repository": "https://github.com/emotion-js/emotion/tree/main/packages/styled",
    "license": "MIT"
  },
  {
    "name": "@emotion/utils",
    "version": "1.4.2",
    "repository": "https://github.com/emotion-js/emotion/tree/main/packages/utils",
    "license": "MIT"
  },
  {
    "name": "@mantine/core",
    "version": "8.3.18",
    "repository": "https://github.com/mantinedev/mantine.git",
    "license": "MIT"
  },
  {
    "name": "@mantine/emotion",
    "version": "8.3.18",
    "repository": "https://github.com/mantinedev/mantine.git",
    "license": "MIT"
  },
  {
    "name": "@mantine/hooks",
    "version": "8.3.18",
    "repository": "https://github.com/mantinedev/mantine.git",
    "license": "MIT"
  },
  {
    "name": "@mantine/notifications",
    "version": "8.3.18",
    "repository": "https://github.com/mantinedev/mantine.git",
    "license": "MIT"
  },
  {
    "name": "@parcel/config-default",
    "version": "2.16.4",
    "repository": "https://github.com/parcel-bundler/parcel.git",
    "license": "MIT"
  },
  {
    "name": "@parcel/transformer-inline-string",
    "version": "2.16.4",
    "repository": "https://github.com/parcel-bundler/parcel.git",
    "license": "MIT"
  },
  {
    "name": "@tabler/icons-react",
    "version": "3.46.0",
    "repository": "https://github.com/tabler/tabler-icons.git",
    "license": "MIT"
  },
  {
    "name": "@tauri-apps/api",
    "version": "2.11.1",
    "repository": "https://github.com/tauri-apps/tauri.git",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "@tauri-apps/cli",
    "version": "2.11.4",
    "repository": "https://github.com/tauri-apps/tauri.git",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "@tauri-apps/plugin-autostart",
    "version": "2.5.1",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "@tauri-apps/plugin-dialog",
    "version": "2.7.3",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "@tauri-apps/plugin-opener",
    "version": "2.5.5",
    "repository": "https://github.com/tauri-apps/plugins-workspace",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "@types/lodash",
    "version": "4.17.25",
    "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
    "license": "MIT"
  },
  {
    "name": "@types/node",
    "version": "26.6.1",
    "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
    "license": "MIT"
  },
  {
    "name": "@types/react",
    "version": "18.3.31",
    "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
    "license": "MIT"
  },
  {
    "name": "@types/react-dom",
    "version": "18.3.7",
    "repository": "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
    "license": "MIT"
  },
  {
    "name": "framer-motion",
    "version": "13.4.0",
    "repository": "https://github.com/motiondivision/motion/",
    "license": "MIT"
  },
  {
    "name": "i18next",
    "version": "26.4.2",
    "repository": "https://github.com/i18next/i18next.git",
    "license": "MIT"
  },
  {
    "name": "lodash",
    "version": "4.18.1",
    "repository": "lodash/lodash",
    "license": "MIT"
  },
  {
    "name": "parcel",
    "version": "2.16.4",
    "repository": "https://github.com/parcel-bundler/parcel.git",
    "license": "MIT"
  },
  {
    "name": "process",
    "version": "0.11.10",
    "repository": "git://github.com/shtylman/node-process.git",
    "license": "MIT"
  },
  {
    "name": "react",
    "version": "18.3.1",
    "repository": "https://github.com/facebook/react.git",
    "license": "MIT"
  },
  {
    "name": "react-dom",
    "version": "18.3.1",
    "repository": "https://github.com/facebook/react.git",
    "license": "MIT"
  },
  {
    "name": "react-i18next",
    "version": "17.0.14",
    "repository": "https://github.com/i18next/react-i18next.git",
    "license": "MIT"
  },
  {
    "name": "react-router",
    "version": "7.18.4",
    "repository": "https://github.com/remix-run/react-router",
    "license": "MIT"
  },
  {
    "name": "react-timeago",
    "version": "8.3.0",
    "repository": "https://github.com/naman34/react-timeago.git",
    "license": "MIT"
  },
  {
    "name": "recoil",
    "version": "0.7.7",
    "repository": "https://github.com/facebookexperimental/Recoil.git",
    "license": "MIT"
  },
  {
    "name": "swr",
    "version": "2.5.1",
    "repository": "github:vercel/swr",
    "license": "MIT"
  },
  {
    "name": "typescript",
    "version": "7.0.2",
    "repository": "https://github.com/microsoft/TypeScript.git",
    "license": "Apache-2.0"
  }
];
