// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a batch of tmutil modifications.
 */
export type ExclusionActionBatch = { 
/**
 * Paths to be added to backup exclusion list.
 */
add: Array<string>, 
/**
 * Paths to be removed from backup exclusion list.
 */
remove: Array<string>, };
