// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metrics = { "files-excluded": number, "files-included": number, "last-excluded": string, "last-excluded-time": number, };
