// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rules to be applied on a specific set of directories.
 */
export type Rule = { 
/**
 * Paths to be excluded.
 */
excludes: Array<string>, 
/**
 * Exclude paths if *any* of these paths exist in the same directory as the path to be excluded.
 */
"if-exists": Array<string>, };
